[package]
name = "snake"
version = "0.1.0"
authors = ["Colin Walker <colinwalker270@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.8"
env_logger = "0.7.1"
serde = "1.0.104"
serde_json = "1.0.44"
